FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
ADD project/test-requirements.txt /code/
RUN pip install -r test-requirements.txt
RUN pip install -r requirements.txt
ADD . /code/
