version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=silk
      - POSTGRES_USER=silk
      - POSTGRES_DB=silk
  web:
    build:
        context: ../
        dockerfile: ./docker/Dockerfile
    command: python /code/project/manage.py runserver 0.0.0.0:8002
    volumes:
      - ../:/code
    environment:
      - PYTHONUNBUFFERED=1
      - LC_CTYPE=fr_FR.UTF-8
      - LANG=fr_FR.UTF-8
      - LC_ALL=fr_FR.UTF-8
      - TERM=xterm
      - DB=postgresql
      - DB_NAME=silk
      - DB_HOST=db
      - DB_USER=silk
      - DB_PASSWORD=silk
    ports:
      - "8002:8002"
    depends_on:
      - db
